-- MEMBER 테이블 생성
CREATE TABLE MEMBER (
    MEMBER_NO VARCHAR(20) NOT NULL PRIMARY KEY,
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(50),
    POINTS INTEGER NOT NULL DEFAULT 0 CHECK (POINTS >= 0),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- 인덱스 생성
CREATE UNIQUE INDEX IDX_MEMBER_LOGIN_ID ON MEMBER(LOGIN_ID);

-- 회원번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호 (고유 식별자)';
COMMENT ON COLUMN MEMBER.LOGIN_ID IS '로그인 아이디';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.PASSWORD IS '암호화된 비밀번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰 번호';
COMMENT ON COLUMN MEMBER.POINTS IS '보유 적립금';
COMMENT ON COLUMN MEMBER.CREATED_AT IS '등록일시';
COMMENT ON COLUMN MEMBER.UPDATED_AT IS '수정일시';
